### ISSUE TITLE
Frage: alt-neu_use_old

### ISSUE THREAD

**Issue by SbSh-DNA-ModDing** [Limone81/FS22-Multi-Terrain-Angle#1]
Bei bereits erweiterten Maps, können diese aber mit dem shader bestehen bleiben oder?

**Comment by Limone81** [comment]
Bei bereits editierten Maps kann der angepasste Shader weiter verwendet werden oder man passt ihn in der i3d auf den Standard-Shader an. Der Pfad wäre dann wieder "$data/shaders/terrainShader.xml"

**Comment by SbSh-DNA-ModDing** [comment]
super, danke
